[project]
name = "genai-pipeline-project"
version = "0.1.0"
dependencies = [
    "feedpoller",
]

[tool.fastapi]
entrypoint = "services.fastapi_app.src.fastapi_app.main:app"

[tool.uv.workspace]
members = [
    "packages/feedpoller",
    "services/fastapi_app",
]

[tool.uv.sources]
feedpoller = { workspace = true }
